### ISSUE TITLE
This was an internal method which is no longer used (Facebook SDK)

### ISSUE THREAD

**Issue by madrobotgames** [PlayFab/UnicornBattle#13]
i just downloaded unity 2017.1 (tried with both Facebook Games Support and without it)

i am getting this error:

Assets/Facebook/Scripts/FB.cs(422,37): error CS0619: `UnityEngine.Security.LoadAndVerifyAssembly(byte[])' is obsolete: `This was an internal method which is no longer used'

as soon as i remember i also got same error in unity 5.6 but not in lower versions.

**Comment by pgilmorepf** [comment]
We definitely had it updated and working for 5.6, so I'm surprised you have issues with that version. Here's the appropriate checkin, 3 months ago:
https://github.com/PlayFab/UnicornBattle/commit/fb4fd3653b2be9544329a3900c0a5eece703c9b1

Unfortunately, I also can't confirm the error you're seeing in 2017.1.  The program built and ran just fine for me just now.  Since you are also seeing an error in 5.6, I assume you haven't updated to the latest version before testing. Please pull the latest changes, make sure you don't have merged and/or resolved all conflicts

**Comment by madrobotgames** [comment]
it looks like unitypackage was not updated and thats why i got the error. i did not use unitypackage that time and it works well.
